client_config_backend: settings
client_config_file: 
	client_id: 162419669862-brl24jr4ps1o2tpt13tlkklicge76dae.apps.googleusercontent.com
	client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credential.json

get_refresh_token: True

oauth_scope:
	- https://www.googleapis.com/auth/drive.file
	- https://www.googleapis.com/auth/drive.install
